# Generated by Django 3.2.4 on 2021-10-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PsychicSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upgradelistitems', models.ManyToManyField(to='armyapp.UpgradeListItems')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipments', models.ManyToManyField(to='armyapp.Equipment')),
                ('specialrules', models.ManyToManyField(to='armyapp.SpecialRule')),
                ('upgrades', models.ManyToManyField(to='armyapp.Upgrade')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='specialrules',
            field=models.ManyToManyField(to='armyapp.SpecialRule'),
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background', models.CharField(max_length=1000)),
                ('pyschicspells', models.ManyToManyField(to='armyapp.PsychicSpell')),
                ('specialrules', models.ManyToManyField(to='armyapp.SpecialRule')),
                ('units', models.ManyToManyField(to='armyapp.Unit')),
                ('upgrades', models.ManyToManyField(to='armyapp.Upgrade')),
            ],
        ),
    ]
