# Generated by Django 3.2.4 on 2021-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='pyschicspells',
            field=models.ManyToManyField(blank=True, to='armyapp.PsychicSpell'),
        ),
        migrations.AlterField(
            model_name='army',
            name='specialrules',
            field=models.ManyToManyField(blank=True, to='armyapp.SpecialRule'),
        ),
        migrations.AlterField(
            model_name='army',
            name='units',
            field=models.ManyToManyField(blank=True, to='armyapp.Unit'),
        ),
        migrations.AlterField(
            model_name='army',
            name='upgrades',
            field=models.ManyToManyField(blank=True, to='armyapp.Upgrade'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specialrules',
            field=models.ManyToManyField(blank=True, to='armyapp.SpecialRule'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='equipments',
            field=models.ManyToManyField(blank=True, to='armyapp.Equipment'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='specialrules',
            field=models.ManyToManyField(blank=True, to='armyapp.SpecialRule'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='upgrades',
            field=models.ManyToManyField(blank=True, to='armyapp.Upgrade'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='upgradelistitems',
            field=models.ManyToManyField(blank=True, to='armyapp.UpgradeListItems'),
        ),
    ]
