# Generated by Django 3.2.4 on 2021-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0002_auto_20211013_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='attacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychicspell',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialrule',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upgradelistitems',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
