# Generated by Django 3.2.4 on 2021-10-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0005_remove_specialrule_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRuleUnitJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True)),
                ('specialrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armyapp.specialrule')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armyapp.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialRuleValue',
        ),
    ]
