# Generated by Django 3.2.4 on 2021-10-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0006_auto_20211013_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='upgrades',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armyapp.army'),
        ),
    ]
