# Generated by Django 3.2.4 on 2021-10-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0007_auto_20211013_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='specialrules',
        ),
    ]
